#!/usr/bin/env bash
LABDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "$LABDIR"/config/calico.cfg

function uninstallKubeadmNode() {
  sudo apt-mark unhold kubeadm kubelet kubectl
  sudo apt-get remove kubeadm kubelet kubectl -y
}

uninstallKubeadmNode
