#!/usr/bin/env bash
LABDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "$LABDIR"/config/calico.cfg

function cleanupHost() {
  sudo rm -rf /var/lib/docker/
  sudo rm -rf /var/lib/kubelet/
  sudo rm -rf /etc/kubernetes/
  sudo rm -rf /opt/cni/
}

cleanupHost
