#!/usr/bin/env bash
LABDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "$LABDIR"/config/calico.cfg

function rebootHost() {
  ( sleep 5 ; sudo reboot ) & 
  exit
}

rebootHost
