#!/usr/bin/env bash
LABDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "$LABDIR"/config/calico.cfg

function resetKubeadmAll() {
  source "${LABDIR}"/000-environment
  setColorOpts

  # Prepare workers:
  printf " \n"
  printf "${BOLD_YELLOW}Syncing remote functions. Please wait...${CLEAR} \n"
  setSshOpts
  syncLabHosts

  # Reset each of the workers:
  printf " \n"
  printf "${BOLD_YELLOW}Resetting each of the workers. Please wait...${CLEAR} \n"
  for i in "${KUBEADM_HOSTS[@]}"; do
  printf "${BOLD_YELLOW}Connecting to ${i}...${CLEAR} \n"
    ssh ${setsshopts:?} ${USER}@${i} -t "${HOME}/.lab/900-kubeadm-reset"
  done

  # Reset the master:
  printf " \n"
  printf "${BOLD_YELLOW}Resetting the master...${CLEAR} \n"
  ${LABDIR}/900-kubeadm-reset
}

resetKubeadmAll
